import type { CanvasLayout, CanvasNode, CanvasNodeId } from "./types";

const DESKTOP_LAYOUT: CanvasLayout = {
  nodeIds: [
    "desktop-greeting",
    "desktop-name",
    "desktop-hero-image",
    "desktop-study-heading",
    "desktop-education-waterloo-image",
    "desktop-education-waterloo-label",
    "desktop-education-waterloo-role",
    "desktop-education-waterloo-year",
    "desktop-education-waterloo-location",
    "desktop-work-heading",
    "desktop-work-ramp-image",
    "desktop-work-ramp-label",
    "desktop-work-ramp-role",
    "desktop-work-ramp-year",
    "desktop-work-ramp-location",
    "desktop-work-uber-image",
    "desktop-work-uber-label",
    "desktop-work-uber-role",
    "desktop-work-uber-year",
    "desktop-work-uber-location",
    "desktop-work-hubspot-image",
    "desktop-work-hubspot-label",
    "desktop-work-hubspot-role",
    "desktop-work-hubspot-year",
    "desktop-work-hubspot-location",
    "desktop-work-bridgewell-image",
    "desktop-work-bridgewell-label",
    "desktop-work-bridgewell-role",
    "desktop-work-bridgewell-year",
    "desktop-work-bridgewell-location",
    "desktop-work-kaimz-image",
    "desktop-work-kaimz-label",
    "desktop-work-kaimz-role",
    "desktop-work-kaimz-year",
    "desktop-work-kaimz-location",
    "desktop-built-heading",
    "desktop-project-phishing-sim-summary",
    "desktop-project-phishing-sim-cta",
    "desktop-project-sales-copilot-summary",
    "desktop-project-sales-copilot-cta",
    "desktop-project-ops-portal-summary",
    "desktop-project-ops-portal-cta",
  ],
  nodes: {
    "desktop-greeting": {
      id: "desktop-greeting",
      type: "text",
      x: 360,
      y: 86,
      width: 286,
      height: 41,
      baseWidth: 286,
      baseHeight: 41,
      fontSize: 34,
      baseFontSize: 34,
      value: "Hey there, I'm",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-name": {
      id: "desktop-name",
      type: "text",
      x: 360,
      y: 147,
      width: 360,
      height: 120,
      baseWidth: 360,
      baseHeight: 120,
      fontSize: 92,
      baseFontSize: 92,
      value: "Jacob Fu",
      sizingMode: "fixed",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 600,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-hero-image": {
      id: "desktop-hero-image",
      alt: "Hero placeholder image",
      src: "/companies/kaimz.png",
      x: 896,
      y: 52,
      width: 300,
      height: 300,
      fit: "cover",
      type: "image",
      baseWidth: 300,
      baseHeight: 300,
    },
    "desktop-study-heading": {
      id: "desktop-study-heading",
      type: "text",
      x: 360,
      y: 406,
      width: 135,
      height: 39,
      baseWidth: 135,
      baseHeight: 39,
      fontSize: 32,
      baseFontSize: 32,
      value: "I study",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-education-waterloo-image": {
      id: "desktop-education-waterloo-image",
      alt: "University of Waterloo logo",
      src: "/companies/waterloo.png",
      x: 360,
      y: 469,
      width: 72,
      height: 72,
      fit: "contain",
      type: "image",
      baseWidth: 72,
      baseHeight: 72,
    },
    "desktop-education-waterloo-label": {
      id: "desktop-education-waterloo-label",
      type: "text",
      x: 456,
      y: 469,
      width: 439,
      height: 27,
      baseWidth: 439,
      baseHeight: 27,
      fontSize: 22,
      baseFontSize: 22,
      value: "University of Waterloo",
      sizingMode: "wrap",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 600,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-education-waterloo-role": {
      id: "desktop-education-waterloo-role",
      type: "text",
      x: 456,
      y: 506,
      width: 183,
      height: 23,
      baseWidth: 183,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "Computer Science",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-education-waterloo-year": {
      id: "desktop-education-waterloo-year",
      type: "text",
      x: 1034,
      y: 469,
      width: 46,
      height: 23,
      baseWidth: 46,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "2028",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-education-waterloo-location": {
      id: "desktop-education-waterloo-location",
      type: "text",
      x: 943,
      y: 502,
      width: 137,
      height: 23,
      baseWidth: 137,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "Waterloo, ON",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-work-heading": {
      id: "desktop-work-heading",
      type: "text",
      x: 360,
      y: 595,
      width: 250,
      height: 39,
      baseWidth: 250,
      baseHeight: 39,
      fontSize: 32,
      baseFontSize: 32,
      value: "I work(ed) at",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-work-ramp-image": {
      id: "desktop-work-ramp-image",
      alt: "Ramp logo",
      src: "/companies/ramp.jpeg",
      x: 360,
      y: 658,
      width: 72,
      height: 72,
      fit: "contain",
      type: "image",
      baseWidth: 72,
      baseHeight: 72,
    },
    "desktop-work-ramp-label": {
      id: "desktop-work-ramp-label",
      type: "text",
      x: 456,
      y: 658,
      width: 77,
      height: 41,
      baseWidth: 77,
      baseHeight: 41,
      fontSize: 22,
      baseFontSize: 22,
      value: "Ramp",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "#ffffff",
      fontWeight: 600,
      paddingX: 12,
      paddingY: 7,
      borderRadius: 16,
    },
    "desktop-work-ramp-role": {
      id: "desktop-work-ramp-role",
      type: "text",
      x: 456,
      y: 709,
      width: 126,
      height: 23,
      baseWidth: 126,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "Engineering",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-work-ramp-year": {
      id: "desktop-work-ramp-year",
      type: "text",
      x: 1034,
      y: 658,
      width: 46,
      height: 23,
      baseWidth: 46,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "2025",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-work-ramp-location": {
      id: "desktop-work-ramp-location",
      type: "text",
      x: 966,
      y: 691,
      width: 114,
      height: 23,
      baseWidth: 114,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "Boston, MA",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-work-uber-image": {
      id: "desktop-work-uber-image",
      alt: "Uber logo",
      src: "/companies/uber.png",
      x: 360,
      y: 760,
      width: 72,
      height: 72,
      fit: "contain",
      type: "image",
      baseWidth: 72,
      baseHeight: 72,
    },
    "desktop-work-uber-label": {
      id: "desktop-work-uber-label",
      type: "text",
      x: 456,
      y: 760,
      width: 77,
      height: 41,
      baseWidth: 77,
      baseHeight: 41,
      fontSize: 22,
      baseFontSize: 22,
      value: "Uber",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "#ffffff",
      fontWeight: 600,
      paddingX: 12,
      paddingY: 7,
      borderRadius: 16,
    },
    "desktop-work-uber-role": {
      id: "desktop-work-uber-role",
      type: "text",
      x: 456,
      y: 811,
      width: 126,
      height: 23,
      baseWidth: 126,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "Engineering",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-work-uber-year": {
      id: "desktop-work-uber-year",
      type: "text",
      x: 1034,
      y: 760,
      width: 46,
      height: 23,
      baseWidth: 46,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "YYYY",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-work-uber-location": {
      id: "desktop-work-uber-location",
      type: "text",
      x: 954,
      y: 793,
      width: 126,
      height: 23,
      baseWidth: 126,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "Toronto, ON",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-work-hubspot-image": {
      id: "desktop-work-hubspot-image",
      alt: "HubSpot logo",
      src: "/companies/hubspot.png",
      x: 360,
      y: 862,
      width: 72,
      height: 72,
      fit: "contain",
      type: "image",
      baseWidth: 72,
      baseHeight: 72,
    },
    "desktop-work-hubspot-label": {
      id: "desktop-work-hubspot-label",
      type: "text",
      x: 456,
      y: 862,
      width: 117,
      height: 41,
      baseWidth: 117,
      baseHeight: 41,
      fontSize: 22,
      baseFontSize: 22,
      value: "HubSpot",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "#ffffff",
      fontWeight: 600,
      paddingX: 12,
      paddingY: 7,
      borderRadius: 16,
    },
    "desktop-work-hubspot-role": {
      id: "desktop-work-hubspot-role",
      type: "text",
      x: 456,
      y: 913,
      width: 126,
      height: 23,
      baseWidth: 126,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "Engineering",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-work-hubspot-year": {
      id: "desktop-work-hubspot-year",
      type: "text",
      x: 1034,
      y: 862,
      width: 46,
      height: 23,
      baseWidth: 46,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "YYYY",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-work-hubspot-location": {
      id: "desktop-work-hubspot-location",
      type: "text",
      x: 931,
      y: 895,
      width: 149,
      height: 23,
      baseWidth: 149,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "Cambridge, MA",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-work-bridgewell-image": {
      id: "desktop-work-bridgewell-image",
      alt: "Bridgewell logo",
      src: "/companies/bridgewell.png",
      x: 360,
      y: 964,
      width: 72,
      height: 72,
      fit: "contain",
      type: "image",
      baseWidth: 72,
      baseHeight: 72,
    },
    "desktop-work-bridgewell-label": {
      id: "desktop-work-bridgewell-label",
      type: "text",
      x: 456,
      y: 964,
      width: 156,
      height: 41,
      baseWidth: 156,
      baseHeight: 41,
      fontSize: 22,
      baseFontSize: 22,
      value: "Bridgewell",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "#ffffff",
      fontWeight: 600,
      paddingX: 12,
      paddingY: 7,
      borderRadius: 16,
    },
    "desktop-work-bridgewell-role": {
      id: "desktop-work-bridgewell-role",
      type: "text",
      x: 456,
      y: 1015,
      width: 126,
      height: 23,
      baseWidth: 126,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "Engineering",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-work-bridgewell-year": {
      id: "desktop-work-bridgewell-year",
      type: "text",
      x: 1034,
      y: 964,
      width: 46,
      height: 23,
      baseWidth: 46,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "YYYY",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-work-bridgewell-location": {
      id: "desktop-work-bridgewell-location",
      type: "text",
      x: 954,
      y: 997,
      width: 126,
      height: 23,
      baseWidth: 126,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "Toronto, ON",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-work-kaimz-image": {
      id: "desktop-work-kaimz-image",
      alt: "Kaimz logo",
      src: "/companies/kaimz.png",
      x: 360,
      y: 1066,
      width: 72,
      height: 72,
      fit: "contain",
      type: "image",
      baseWidth: 72,
      baseHeight: 72,
    },
    "desktop-work-kaimz-label": {
      id: "desktop-work-kaimz-label",
      type: "text",
      x: 456,
      y: 1066,
      width: 90,
      height: 41,
      baseWidth: 90,
      baseHeight: 41,
      fontSize: 22,
      baseFontSize: 22,
      value: "Kaimz",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "#ffffff",
      fontWeight: 600,
      paddingX: 12,
      paddingY: 7,
      borderRadius: 16,
    },
    "desktop-work-kaimz-role": {
      id: "desktop-work-kaimz-role",
      type: "text",
      x: 456,
      y: 1117,
      width: 126,
      height: 23,
      baseWidth: 126,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "Engineering",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-work-kaimz-year": {
      id: "desktop-work-kaimz-year",
      type: "text",
      x: 1034,
      y: 1066,
      width: 46,
      height: 23,
      baseWidth: 46,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "YYYY",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-work-kaimz-location": {
      id: "desktop-work-kaimz-location",
      type: "text",
      x: 954,
      y: 1099,
      width: 126,
      height: 23,
      baseWidth: 126,
      baseHeight: 23,
      fontSize: 19,
      baseFontSize: 19,
      value: "Toronto, ON",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-built-heading": {
      id: "desktop-built-heading",
      type: "text",
      x: 360,
      y: 1194,
      width: 192,
      height: 39,
      baseWidth: 192,
      baseHeight: 39,
      fontSize: 32,
      baseFontSize: 32,
      value: "I've built",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-project-phishing-sim-summary": {
      id: "desktop-project-phishing-sim-summary",
      type: "text",
      x: 360,
      y: 1257,
      width: 622,
      height: 27,
      baseWidth: 622,
      baseHeight: 27,
      fontSize: 22,
      baseFontSize: 22,
      value: "Phishing simulator for banks aspdo kaspd",
      sizingMode: "wrap",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-project-phishing-sim-cta": {
      id: "desktop-project-phishing-sim-cta",
      type: "text",
      x: 1008,
      y: 1257,
      width: 72,
      height: 24,
      baseWidth: 72,
      baseHeight: 24,
      fontSize: 20,
      baseFontSize: 20,
      value: "GitHub",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-project-sales-copilot-summary": {
      id: "desktop-project-sales-copilot-summary",
      type: "text",
      x: 360,
      y: 1312,
      width: 622,
      height: 27,
      baseWidth: 622,
      baseHeight: 27,
      fontSize: 22,
      baseFontSize: 22,
      value: "Realtime meeting copilot for sales teams",
      sizingMode: "wrap",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-project-sales-copilot-cta": {
      id: "desktop-project-sales-copilot-cta",
      type: "text",
      x: 1008,
      y: 1312,
      width: 72,
      height: 24,
      baseWidth: 72,
      baseHeight: 24,
      fontSize: 20,
      baseFontSize: 20,
      value: "GitHub",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-project-ops-portal-summary": {
      id: "desktop-project-ops-portal-summary",
      type: "text",
      x: 360,
      y: 1367,
      width: 622,
      height: 27,
      baseWidth: 622,
      baseHeight: 27,
      fontSize: 22,
      baseFontSize: 22,
      value: "Interactive onboarding portal for fintech ops",
      sizingMode: "wrap",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "desktop-project-ops-portal-cta": {
      id: "desktop-project-ops-portal-cta",
      type: "text",
      x: 1008,
      y: 1367,
      width: 72,
      height: 24,
      baseWidth: 72,
      baseHeight: 24,
      fontSize: 20,
      baseFontSize: 20,
      value: "GitHub",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
  },
};

const MOBILE_LAYOUT: CanvasLayout = {
  nodeIds: [
    "mobile-greeting",
    "mobile-name",
    "mobile-hero-image",
    "mobile-study-heading",
    "mobile-education-waterloo-image",
    "mobile-education-waterloo-label",
    "mobile-education-waterloo-role",
    "mobile-education-waterloo-year",
    "mobile-education-waterloo-location",
    "mobile-work-heading",
    "mobile-work-ramp-image",
    "mobile-work-ramp-label",
    "mobile-work-ramp-role",
    "mobile-work-ramp-year",
    "mobile-work-ramp-location",
    "mobile-work-uber-image",
    "mobile-work-uber-label",
    "mobile-work-uber-role",
    "mobile-work-uber-year",
    "mobile-work-uber-location",
    "mobile-work-hubspot-image",
    "mobile-work-hubspot-label",
    "mobile-work-hubspot-role",
    "mobile-work-hubspot-year",
    "mobile-work-hubspot-location",
    "mobile-work-bridgewell-image",
    "mobile-work-bridgewell-label",
    "mobile-work-bridgewell-role",
    "mobile-work-bridgewell-year",
    "mobile-work-bridgewell-location",
    "mobile-work-kaimz-image",
    "mobile-work-kaimz-label",
    "mobile-work-kaimz-role",
    "mobile-work-kaimz-year",
    "mobile-work-kaimz-location",
    "mobile-built-heading",
    "mobile-project-phishing-sim-summary",
    "mobile-project-phishing-sim-cta",
    "mobile-project-sales-copilot-summary",
    "mobile-project-sales-copilot-cta",
    "mobile-project-ops-portal-summary",
    "mobile-project-ops-portal-cta",
  ],
  nodes: {
    "mobile-greeting": {
      id: "mobile-greeting",
      type: "text",
      x: 20,
      y: 46,
      width: 202,
      height: 29,
      baseWidth: 202,
      baseHeight: 29,
      fontSize: 24,
      baseFontSize: 24,
      value: "Hey there, I'm",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-name": {
      id: "mobile-name",
      type: "text",
      x: 20,
      y: 91,
      width: 212,
      height: 92,
      baseWidth: 212,
      baseHeight: 92,
      fontSize: 58,
      baseFontSize: 58,
      value: "Jacob Fu",
      sizingMode: "fixed",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 600,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-hero-image": {
      id: "mobile-hero-image",
      alt: "Hero placeholder image",
      src: "/companies/kaimz.png",
      x: 236,
      y: 24,
      width: 144,
      height: 144,
      fit: "cover",
      type: "image",
      baseWidth: 144,
      baseHeight: 144,
    },
    "mobile-study-heading": {
      id: "mobile-study-heading",
      type: "text",
      x: 20,
      y: 221,
      width: 101,
      height: 29,
      baseWidth: 101,
      baseHeight: 29,
      fontSize: 24,
      baseFontSize: 24,
      value: "I study",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-education-waterloo-image": {
      id: "mobile-education-waterloo-image",
      alt: "University of Waterloo logo",
      src: "/companies/waterloo.png",
      x: 20,
      y: 272,
      width: 44,
      height: 44,
      fit: "contain",
      type: "image",
      baseWidth: 44,
      baseHeight: 44,
    },
    "mobile-education-waterloo-label": {
      id: "mobile-education-waterloo-label",
      type: "text",
      x: 82,
      y: 272,
      width: 140,
      height: 41,
      baseWidth: 140,
      baseHeight: 41,
      fontSize: 17,
      baseFontSize: 17,
      value: "University of Waterloo",
      sizingMode: "wrap",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 600,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-education-waterloo-role": {
      id: "mobile-education-waterloo-role",
      type: "text",
      x: 82,
      y: 321,
      width: 144,
      height: 18,
      baseWidth: 144,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "Computer Science",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-education-waterloo-year": {
      id: "mobile-education-waterloo-year",
      type: "text",
      x: 318,
      y: 272,
      width: 36,
      height: 18,
      baseWidth: 36,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "2028",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-education-waterloo-location": {
      id: "mobile-education-waterloo-location",
      type: "text",
      x: 246,
      y: 298,
      width: 108,
      height: 18,
      baseWidth: 108,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "Waterloo, ON",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-work-heading": {
      id: "mobile-work-heading",
      type: "text",
      x: 20,
      y: 377,
      width: 188,
      height: 29,
      baseWidth: 188,
      baseHeight: 29,
      fontSize: 24,
      baseFontSize: 24,
      value: "I work(ed) at",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-work-ramp-image": {
      id: "mobile-work-ramp-image",
      alt: "Ramp logo",
      src: "/companies/ramp.jpeg",
      x: 20,
      y: 428,
      width: 44,
      height: 44,
      fit: "contain",
      type: "image",
      baseWidth: 44,
      baseHeight: 44,
    },
    "mobile-work-ramp-label": {
      id: "mobile-work-ramp-label",
      type: "text",
      x: 82,
      y: 428,
      width: 65,
      height: 35,
      baseWidth: 65,
      baseHeight: 35,
      fontSize: 17,
      baseFontSize: 17,
      value: "Ramp",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "#ffffff",
      fontWeight: 600,
      paddingX: 12,
      paddingY: 7,
      borderRadius: 16,
    },
    "mobile-work-ramp-role": {
      id: "mobile-work-ramp-role",
      type: "text",
      x: 82,
      y: 471,
      width: 99,
      height: 18,
      baseWidth: 99,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "Engineering",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-work-ramp-year": {
      id: "mobile-work-ramp-year",
      type: "text",
      x: 304,
      y: 428,
      width: 36,
      height: 18,
      baseWidth: 36,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "2025",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-work-ramp-location": {
      id: "mobile-work-ramp-location",
      type: "text",
      x: 250,
      y: 454,
      width: 90,
      height: 18,
      baseWidth: 90,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "Boston, MA",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-work-uber-image": {
      id: "mobile-work-uber-image",
      alt: "Uber logo",
      src: "/companies/uber.png",
      x: 20,
      y: 511,
      width: 44,
      height: 44,
      fit: "contain",
      type: "image",
      baseWidth: 44,
      baseHeight: 44,
    },
    "mobile-work-uber-label": {
      id: "mobile-work-uber-label",
      type: "text",
      x: 82,
      y: 511,
      width: 65,
      height: 35,
      baseWidth: 65,
      baseHeight: 35,
      fontSize: 17,
      baseFontSize: 17,
      value: "Uber",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "#ffffff",
      fontWeight: 600,
      paddingX: 12,
      paddingY: 7,
      borderRadius: 16,
    },
    "mobile-work-uber-role": {
      id: "mobile-work-uber-role",
      type: "text",
      x: 82,
      y: 554,
      width: 99,
      height: 18,
      baseWidth: 99,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "Engineering",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-work-uber-year": {
      id: "mobile-work-uber-year",
      type: "text",
      x: 304,
      y: 511,
      width: 36,
      height: 18,
      baseWidth: 36,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "YYYY",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-work-uber-location": {
      id: "mobile-work-uber-location",
      type: "text",
      x: 241,
      y: 537,
      width: 99,
      height: 18,
      baseWidth: 99,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "Toronto, ON",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-work-hubspot-image": {
      id: "mobile-work-hubspot-image",
      alt: "HubSpot logo",
      src: "/companies/hubspot.png",
      x: 20,
      y: 594,
      width: 44,
      height: 44,
      fit: "contain",
      type: "image",
      baseWidth: 44,
      baseHeight: 44,
    },
    "mobile-work-hubspot-label": {
      id: "mobile-work-hubspot-label",
      type: "text",
      x: 82,
      y: 594,
      width: 96,
      height: 35,
      baseWidth: 96,
      baseHeight: 35,
      fontSize: 17,
      baseFontSize: 17,
      value: "HubSpot",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "#ffffff",
      fontWeight: 600,
      paddingX: 12,
      paddingY: 7,
      borderRadius: 16,
    },
    "mobile-work-hubspot-role": {
      id: "mobile-work-hubspot-role",
      type: "text",
      x: 82,
      y: 637,
      width: 99,
      height: 18,
      baseWidth: 99,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "Engineering",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-work-hubspot-year": {
      id: "mobile-work-hubspot-year",
      type: "text",
      x: 304,
      y: 594,
      width: 36,
      height: 18,
      baseWidth: 36,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "YYYY",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-work-hubspot-location": {
      id: "mobile-work-hubspot-location",
      type: "text",
      x: 223,
      y: 620,
      width: 117,
      height: 18,
      baseWidth: 117,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "Cambridge, MA",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-work-bridgewell-image": {
      id: "mobile-work-bridgewell-image",
      alt: "Bridgewell logo",
      src: "/companies/bridgewell.png",
      x: 20,
      y: 677,
      width: 44,
      height: 44,
      fit: "contain",
      type: "image",
      baseWidth: 44,
      baseHeight: 44,
    },
    "mobile-work-bridgewell-label": {
      id: "mobile-work-bridgewell-label",
      type: "text",
      x: 82,
      y: 677,
      width: 126,
      height: 35,
      baseWidth: 126,
      baseHeight: 35,
      fontSize: 17,
      baseFontSize: 17,
      value: "Bridgewell",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "#ffffff",
      fontWeight: 600,
      paddingX: 12,
      paddingY: 7,
      borderRadius: 16,
    },
    "mobile-work-bridgewell-role": {
      id: "mobile-work-bridgewell-role",
      type: "text",
      x: 82,
      y: 720,
      width: 99,
      height: 18,
      baseWidth: 99,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "Engineering",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-work-bridgewell-year": {
      id: "mobile-work-bridgewell-year",
      type: "text",
      x: 304,
      y: 677,
      width: 36,
      height: 18,
      baseWidth: 36,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "YYYY",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-work-bridgewell-location": {
      id: "mobile-work-bridgewell-location",
      type: "text",
      x: 241,
      y: 703,
      width: 99,
      height: 18,
      baseWidth: 99,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "Toronto, ON",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-work-kaimz-image": {
      id: "mobile-work-kaimz-image",
      alt: "Kaimz logo",
      src: "/companies/kaimz.png",
      x: 20,
      y: 760,
      width: 44,
      height: 44,
      fit: "contain",
      type: "image",
      baseWidth: 44,
      baseHeight: 44,
    },
    "mobile-work-kaimz-label": {
      id: "mobile-work-kaimz-label",
      type: "text",
      x: 82,
      y: 760,
      width: 75,
      height: 35,
      baseWidth: 75,
      baseHeight: 35,
      fontSize: 17,
      baseFontSize: 17,
      value: "Kaimz",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "#ffffff",
      fontWeight: 600,
      paddingX: 12,
      paddingY: 7,
      borderRadius: 16,
    },
    "mobile-work-kaimz-role": {
      id: "mobile-work-kaimz-role",
      type: "text",
      x: 82,
      y: 803,
      width: 99,
      height: 18,
      baseWidth: 99,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "Engineering",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-work-kaimz-year": {
      id: "mobile-work-kaimz-year",
      type: "text",
      x: 304,
      y: 760,
      width: 36,
      height: 18,
      baseWidth: 36,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "YYYY",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-work-kaimz-location": {
      id: "mobile-work-kaimz-location",
      type: "text",
      x: 241,
      y: 786,
      width: 99,
      height: 18,
      baseWidth: 99,
      baseHeight: 18,
      fontSize: 15,
      baseFontSize: 15,
      value: "Toronto, ON",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-built-heading": {
      id: "mobile-built-heading",
      type: "text",
      x: 20,
      y: 859,
      width: 144,
      height: 29,
      baseWidth: 144,
      baseHeight: 29,
      fontSize: 24,
      baseFontSize: 24,
      value: "I've built",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-project-phishing-sim-summary": {
      id: "mobile-project-phishing-sim-summary",
      type: "text",
      x: 20,
      y: 910,
      width: 237,
      height: 44,
      baseWidth: 237,
      baseHeight: 44,
      fontSize: 18,
      baseFontSize: 18,
      value: "Phishing simulator for banks aspdo kaspd",
      sizingMode: "wrap",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-project-phishing-sim-cta": {
      id: "mobile-project-phishing-sim-cta",
      type: "text",
      x: 275,
      y: 910,
      width: 65,
      height: 22,
      baseWidth: 65,
      baseHeight: 22,
      fontSize: 18,
      baseFontSize: 18,
      value: "GitHub",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-project-sales-copilot-summary": {
      id: "mobile-project-sales-copilot-summary",
      type: "text",
      x: 20,
      y: 976,
      width: 237,
      height: 44,
      baseWidth: 237,
      baseHeight: 44,
      fontSize: 18,
      baseFontSize: 18,
      value: "Realtime meeting copilot for sales teams",
      sizingMode: "wrap",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-project-sales-copilot-cta": {
      id: "mobile-project-sales-copilot-cta",
      type: "text",
      x: 275,
      y: 976,
      width: 65,
      height: 22,
      baseWidth: 65,
      baseHeight: 22,
      fontSize: 18,
      baseFontSize: 18,
      value: "GitHub",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-project-ops-portal-summary": {
      id: "mobile-project-ops-portal-summary",
      type: "text",
      x: 20,
      y: 1042,
      width: 237,
      height: 65,
      baseWidth: 237,
      baseHeight: 65,
      fontSize: 18,
      baseFontSize: 18,
      value: "Interactive onboarding portal for fintech ops",
      sizingMode: "wrap",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
    "mobile-project-ops-portal-cta": {
      id: "mobile-project-ops-portal-cta",
      type: "text",
      x: 275,
      y: 1042,
      width: 65,
      height: 22,
      baseWidth: 65,
      baseHeight: 22,
      fontSize: 18,
      baseFontSize: 18,
      value: "GitHub",
      sizingMode: "hug",
      textColor: "#0f172a",
      backgroundColor: "transparent",
      fontWeight: 500,
      paddingX: 0,
      paddingY: 0,
      borderRadius: 0,
    },
  },
};

/**
 * Clones a layout preset so editing session state cannot mutate the authored
 * preset objects by reference.
 */
export function cloneLayout(layout: CanvasLayout): CanvasLayout {
  return {
    nodeIds: [...layout.nodeIds],
    nodes: Object.fromEntries(
      Object.entries(layout.nodes).map(([id, node]) => [id, cloneNode(node)]),
    ) as Record<CanvasNodeId, CanvasNode>,
  };
}

function cloneNode(node: CanvasNode): CanvasNode {
  return { ...node };
}

export const LAYOUT_PRESETS = {
  desktop: DESKTOP_LAYOUT,
  mobile: MOBILE_LAYOUT,
} as const;
